[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["npm ci --include=dev --no-audit --no-fund"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=4096' npm run build"]

[start]
cmd = "node dist/index.js"
