export interface PortfolioProfile {
  contentVersion?: number;
  name: string;
  eyebrow: string;
  headline: string;
  summary: string;
  bio: string;
  location: string;
  email: string;
  portraitUrl: string;
  cvUrl: string;
  socialLinks: Array<{ label: string; url: string }>;
  skills: string[];
  services: string[];
}

export interface PortfolioProject {
  slug: string;
  title: string;
  category: string;
  year: string;
  summary: string;
  description: string;
  role: string;
  technologies: string[];
  outcomes: string[];
  imageUrl: string;
  liveUrl: string;
  featured: boolean;
  visible: boolean;
  sortOrder: number;
}

const projectImage = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const DEFAULT_PORTFOLIO_PROFILE: PortfolioProfile = {
  contentVersion: 2,
  name: "Abraham Tahbat",
  eyebrow: "Founder & CTO · Full-Stack AI Developer · Lawyer",
  headline: "I build the digital products ambitious businesses need next.",
  summary: "Founder, CTO, lawyer and product architect creating marketplaces, SaaS platforms, AI tools, and business systems that turn complex ideas into clear, useful experiences.",
  bio: "I am Abraham Tahbat — Founder and CTO of Breedskool Galaxy and Taskdrip, a lawyer called to the Nigerian Bar in 2015, and a full-stack web developer who followed a passion for entrepreneurship and information technology. I build products, create content, apply AI to practical business problems, shape go-to-market strategy, and help teams move from an idea to a dependable digital business.",
  location: "Nigeria · Working globally",
  email: "taskdrip@gmail.com",
  portraitUrl: "/portfolio/abraham-portrait.jpg",
  cvUrl: "/portfolio/abraham-cv.pdf",
  socialLinks: [
    { label: "LinkedIn", url: "https://www.linkedin.com/in/taskdrip/" },
    { label: "Instagram", url: "https://www.instagram.com/taskdriper" },
    { label: "X", url: "https://x.com/taskdrip" },
    { label: "YouTube", url: "https://www.youtube.com/@Taskdriper" },
  ],
  skills: [
    "JavaScript", "TypeScript", "React", "Next.js", "Node.js", "Express.js",
    "PostgreSQL", "MongoDB", "REST APIs", "AI integration", "Railway deployment",
    "WordPress", "SEO", "UI/UX", "Product strategy", "Digital marketing",
    "Content creation", "Legal technology", "Business automation",
  ],
  services: [
    "SaaS product architecture and full-stack development",
    "AI-powered application development and automation",
    "Marketplace, logistics, and LMS development",
    "Digital transformation and growth strategy",
    "Product positioning, content, and go-to-market",
  ],
};

export const DEFAULT_PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    slug: "taskdrip",
    title: "Taskdrip",
    category: "Marketplace · Fintech · Learning",
    year: "2025–Present",
    summary: "A creator marketplace that connects brands and influencers through campaigns, escrow, direct hire, and education.",
    description: "Taskdrip brings creator discovery, campaign operations, crypto-enabled payments, digital products, community, and BreedSkool learning into one platform. The product is designed around trust: verified profiles, structured campaign submissions, admin-controlled payment flows, and clear progress visibility.",
    role: "Founder · Product architect · Lead engineer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Drizzle ORM", "WebSockets", "Railway"],
    outcomes: ["One workspace for creator campaigns, products, education, and direct hire", "Escrow and review flows designed around transparent delivery", "Admin tooling for content, payments, users, and operations"],
    imageUrl: projectImage("photo-1556761175-b413da4baf72"),
    liveUrl: "https://taskdrip.online",
    featured: true,
    visible: true,
    sortOrder: 1,
  },
  {
    slug: "beagvs-marine",
    title: "Beagvs Marine",
    category: "Marketplace · Real Estate · Logistics",
    year: "2024–Present",
    summary: "A multi-category marketplace for real estate, products, and services with a complete shipping and logistics experience.",
    description: "Beagvs Marine brings property, products, services, and fulfilment into one marketplace experience. The platform is designed to make discovery feel simple while supporting the operational detail behind enquiries, orders, shipping, and logistics.",
    role: "Founder · Product architect · Full-stack developer",
    technologies: ["React", "Node.js", "PostgreSQL", "Marketplace UX", "Logistics workflows"],
    outcomes: ["One marketplace experience across property, products, and services", "Operational foundation for shipping and fulfilment", "Conversion-focused discovery and enquiry flows"],
    imageUrl: projectImage("photo-1494412574643-ff11b0a5c1c3"),
    liveUrl: "https://beagvsmarine.com/",
    featured: true,
    visible: true,
    sortOrder: 2,
  },
  {
    slug: "lawcolab",
    title: "LAWCOLAB",
    category: "LegalTech · SaaS",
    year: "2024–Present",
    summary: "A complete law-firm management web app for matters, clients, documents, billing, team operations, and client portals.",
    description: "LAWCOLAB turns everyday law-firm operations into a connected workspace. It supports client and matter management, document workflows, billing, team visibility, firm isolation, and a client portal — shaped by real legal practice knowledge and software discipline.",
    role: "Founder · Product architect · Lead engineer",
    technologies: ["Python", "Flask", "PostgreSQL", "REST APIs", "Multi-tenant SaaS", "RBAC"],
    outcomes: ["Connected workflows for modern law firms", "Multi-tenant foundation for solo practitioners and growing firms", "A secure bridge between legal expertise and operational software"],
    imageUrl: projectImage("photo-1450101499163-c8848c66ca85"),
    liveUrl: "https://lawcolab-production.up.railway.app",
    featured: true,
    visible: true,
    sortOrder: 3,
  },
  {
    slug: "stageplug",
    title: "StagePlug",
    category: "Music · Entertainment · SaaS",
    year: "2024–Present",
    summary: "A music empire and record-label management web app for artists, releases, opportunities, and the business behind the stage.",
    description: "StagePlug is a digital operating layer for music and entertainment businesses. It brings artists, releases, label operations, opportunities, and production needs into a structured experience built to support both discovery and execution.",
    role: "Founder · Product architect · Full-stack developer",
    technologies: ["React", "Node.js", "PostgreSQL", "Marketplace UX", "Media workflows"],
    outcomes: ["A focused home for artists, labels, and entertainment opportunities", "Structured workflows for releases and production operations", "A product foundation for growth across the music ecosystem"],
    imageUrl: projectImage("photo-1501281668745-f7f57925c3b4"),
    liveUrl: "https://stageplug-production.up.railway.app/",
    featured: true,
    visible: true,
    sortOrder: 4,
  },
  {
    slug: "the-industry-miner",
    title: "The Industry Miner",
    category: "Entrepreneurship · Mentorship · Community",
    year: "2024–Present",
    summary: "An entrepreneurship and mentorship platform connecting ambitious people with practical industry insight and guidance.",
    description: "The Industry Miner creates a more discoverable home for entrepreneurship content, mentorship, stories, and opportunities. The experience makes dense industry knowledge approachable while leaving room for community, programmes, and sponsored learning.",
    role: "Founder · Product strategist · Developer",
    technologies: ["React", "Content systems", "SEO", "Editorial UX", "Community workflows"],
    outcomes: ["A structured publishing experience for industry-focused content", "Clear pathways from discovery to deeper learning", "A flexible platform for mentorship, research, and community"],
    imageUrl: projectImage("photo-1454165804606-c3d57bc86b40"),
    liveUrl: "https://theindustryminer.com/",
    featured: true,
    visible: true,
    sortOrder: 5,
  },
  {
    slug: "replit-saas-starter",
    title: "Replit SaaS Starter Project",
    category: "Software Product · SaaS",
    year: "2024",
    summary: "A production-minded starter codebase for launching authenticated, data-driven SaaS products faster.",
    description: "The Replit SaaS Starter Project packages the recurring foundations of a modern SaaS product: authentication, dashboards, payments, content, database-backed workflows, and deployment practices. It is built for founders who want to spend their energy on differentiation rather than reinvention.",
    role: "Software architect · Developer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Drizzle ORM", "Vite"],
    outcomes: ["Reusable foundations for new SaaS products", "A practical bridge from prototype to production", "Faster delivery without hiding the important engineering decisions"],
    imageUrl: projectImage("photo-1560518883-ce09059eeffa"),
    liveUrl: "/shop/product/80970463-963e-4a1a-8cfa-e3531261bcc7",
    featured: false,
    visible: true,
    sortOrder: 6,
  },
  {
    slug: "github-repo-growth-kit",
    title: "GitHub Repo Growth Kit",
    category: "Developer Tools · Documentation",
    year: "2023",
    summary: "A documentation and repository presentation system that helps software projects earn trust.",
    description: "The GitHub Repo Growth Kit treats documentation as part of the product experience. It gives maintainers a clearer structure for README content, contribution guidance, issue templates, releases, and the first impression that turns a visitor into a user or contributor.",
    role: "Developer experience designer · Developer",
    technologies: ["GitHub", "Documentation systems", "Markdown", "Open-source workflows"],
    outcomes: ["More navigable repositories for users and contributors", "Repeatable documentation patterns for new projects", "A stronger connection between code quality and product communication"],
    imageUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1400&q=82",
    liveUrl: "/shop/product/d576b928-6208-442d-91fd-880627c1e875",
    featured: false,
    visible: true,
    sortOrder: 7,
  },
  {
    slug: "personal-brand-strategy-guide",
    title: "Personal Brand Strategy Guide",
    category: "Strategy · Digital Product",
    year: "2023–Present",
    summary: "A guided digital product for creators and professionals shaping a clearer personal brand.",
    description: "The Personal Brand Strategy Guide helps users move from a vague sense of what they do to a clearer positioning story. It combines prompts, frameworks, and practical next steps so the result can live across a profile, portfolio, and content plan.",
    role: "Brand strategist · Product designer",
    technologies: ["Brand strategy", "UX writing", "Digital publishing", "Content design"],
    outcomes: ["A clearer process for defining a differentiated point of view", "Frameworks that translate into content and profile decisions", "A reusable digital product for personal brand workshops"],
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1400&q=82",
    liveUrl: "/shop/product/b2029709-92b1-4fe9-b664-be40a1167c72",
    featured: false,
    visible: true,
    sortOrder: 8,
  },
  {
    slug: "content-influencer-toolkit",
    title: "Content Influencer Toolkit",
    category: "Creator Tools · Productivity",
    year: "2023",
    summary: "A collection of practical workflows and tools for creators building a consistent publishing business.",
    description: "The Content Influencer Toolkit brings planning, content operations, and creator resources into a single product direction. It is intentionally practical: reduce the blank-page problem, make repeatable work easier, and keep the creator focused on their audience.",
    role: "Product strategist · Developer",
    technologies: ["React", "Content workflows", "UI systems", "Digital products"],
    outcomes: ["A cohesive home for everyday creator workflows", "Reusable patterns for tool and resource libraries", "A product foundation that supports both free and premium content"],
    imageUrl: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1400&q=82",
    liveUrl: "/shop/product/1e43245b-c673-4944-91c6-9f2d5e0c74c3",
    featured: false,
    visible: true,
    sortOrder: 9,
  },
  {
    slug: "hashtag-research-tool-pro",
    title: "Hashtag Research Tool Pro",
    category: "Creator Tools · Analytics",
    year: "2023",
    summary: "A focused research tool for helping creators make more informed content distribution choices.",
    description: "Hashtag Research Tool Pro turns a noisy discovery problem into a more focused research workflow. The product direction is centered on useful filtering, understandable signals, and decisions creators can act on immediately.",
    role: "Product architect · Developer",
    technologies: ["React", "Data visualization", "Search UX", "API integration"],
    outcomes: ["More deliberate discovery and content planning", "Signals presented in a way non-technical users can understand", "A modular base for broader creator analytics"],
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1400&q=82",
    liveUrl: "/shop/product/8426d252-058e-483f-b825-f07f0db5181f",
    featured: false,
    visible: true,
    sortOrder: 10,
  },
  {
    slug: "influencer-media-kit",
    title: "Influencer Media Kit Template",
    category: "Creator Tools · Template",
    year: "2023",
    summary: "A polished media kit system that helps creators present their audience, services, and partnership value.",
    description: "The Influencer Media Kit gives creators a stronger way to communicate who they are and how brands can work with them. The design focuses on scannable proof, clear offers, and a personal brand presentation that feels more considered than a collection of social links.",
    role: "Product designer · Developer",
    technologies: ["React", "Responsive UI", "Brand systems", "Creator UX"],
    outcomes: ["A clear narrative for creator-brand conversations", "Reusable content blocks for different creator niches", "A stronger bridge between audience data and commercial opportunity"],
    imageUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=1400&q=82",
    liveUrl: "/shop/product/8b6297c4-887d-4abf-8f93-e70b8e2b4b80",
    featured: false,
    visible: true,
    sortOrder: 11,
  },
  {
    slug: "viral-content-templates",
    title: "Viral Content Templates Pack",
    category: "Creator Tools · Template",
    year: "2023",
    summary: "A practical content template library for creators who need repeatable ideas and faster production.",
    description: "Viral Content Templates organizes content prompts and formats into a usable system rather than a static list of inspiration. It is designed to help creators move from an idea to a publishable brief with less friction.",
    role: "Content product designer · Developer",
    technologies: ["Content systems", "React", "UX writing", "Information architecture"],
    outcomes: ["Faster discovery of relevant content formats", "A repeatable workflow for planning creator output", "A foundation for personalization by niche and platform"],
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1400&q=82",
    liveUrl: "/shop/product/f2f9ef2c-4994-4878-ac1e-4bbdd0f518ce",
    featured: false,
    visible: true,
    sortOrder: 12,
  },
  {
    slug: "ai-ebook-generator",
    title: "AI Ebook Generator",
    category: "AI · Content Tools",
    year: "2023",
    summary: "An AI-assisted workflow for turning ideas into structured ebook drafts and publishable content.",
    description: "The AI Ebook Generator explores how generative AI can support authors and businesses without hiding the human in the process. The workflow emphasizes guided inputs, useful structure, editing, and export rather than one-click noise.",
    role: "AI product architect · Developer",
    technologies: ["AI APIs", "React", "Node.js", "Prompt design", "Document workflows"],
    outcomes: ["Guided creation flow from concept to structured draft", "Human-in-the-loop editing as a first-class step", "A reusable pattern for AI-assisted business content"],
    imageUrl: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1400&q=82",
    liveUrl: "/shop",
    featured: false,
    visible: true,
    sortOrder: 13,
  },
  {
    slug: "property-os",
    title: "Property OS",
    category: "PropTech · SaaS",
    year: "2023",
    summary: "A property management SaaS concept for organizing properties, tenants, maintenance, and business operations.",
    description: "Property OS brings the operational side of property management into one place. The product direction focuses on replacing fragmented spreadsheets and chat threads with structured records, task visibility, and actionable dashboards.",
    role: "Product architect · Full-stack developer",
    technologies: ["React", "Node.js", "PostgreSQL", "Dashboards", "Workflow automation"],
    outcomes: ["Centralized view of property operations", "Clearer workflows for recurring management tasks", "An extensible platform direction for landlords and property teams"],
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=82",
    liveUrl: "/shop",
    featured: false,
    visible: true,
    sortOrder: 14,
  },
  {
    slug: "breedskool-lms",
    title: "BreedSkool Galaxy LMS",
    category: "EdTech · Learning",
    year: "2023",
    summary: "A learning platform for practical technology training, courses, lessons, certificates, and community.",
    description: "BreedSkool extends the mission of Breedskool Galaxy Ltd into a modern learning experience. It supports course discovery, structured lessons, enrollment, progress, certificates, and training operations designed for aspiring creators and digital professionals.",
    role: "Founder · Learning product architect · Developer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Course workflows"],
    outcomes: ["Learning journeys that connect lessons to visible progress", "Admin controls for courses, pricing, enrollments, and certificates", "A scalable home for practical digital skills training"],
    imageUrl: projectImage("photo-1522202176988-66273c2fd55f"),
    liveUrl: "/breedskool",
    featured: false,
    visible: true,
    sortOrder: 15,
  },
];

export const PORTFOLIO_CONTENT_KEYS = {
  profile: "portfolio_abraham_profile",
  projects: "portfolio_abraham_projects",
} as const;