export interface PortfolioProfile {
  name: string;
  eyebrow: string;
  headline: string;
  summary: string;
  bio: string;
  location: string;
  email: string;
  portraitUrl: string;
  cvUrl: string;
  socialLinks: Array<{ label: string; url: string }>;
  skills: string[];
  services: string[];
}

export interface PortfolioProject {
  slug: string;
  title: string;
  category: string;
  year: string;
  summary: string;
  description: string;
  role: string;
  technologies: string[];
  outcomes: string[];
  imageUrl: string;
  liveUrl: string;
  featured: boolean;
  visible: boolean;
  sortOrder: number;
}

const projectImage = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const DEFAULT_PORTFOLIO_PROFILE: PortfolioProfile = {
  name: "Abraham Felix Tahbat",
  eyebrow: "Full-Stack AI SaaS Developer · Product Architect · Lawyer",
  headline: "I turn ambitious ideas into useful digital products.",
  summary: "A product-minded engineer and digital transformation consultant building scalable SaaS platforms, AI-powered tools, marketplaces, and business systems.",
  bio: "I am Abraham Felix Tahbat, a full-stack developer with 14+ years of web development experience, building professionally since 2012. I founded Breedskool Galaxy Ltd in 2015 as a web development, branding, digital marketing, and technology training institute. My work sits at the intersection of product strategy, thoughtful UX, reliable engineering, and practical business outcomes.",
  location: "Nigeria · Working globally",
  email: "tremendouslymax@gmail.com",
  portraitUrl: "/api/portfolio-assets/portrait",
  cvUrl: "/api/portfolio-assets/cv",
  socialLinks: [
    { label: "Taskdrip", url: "https://taskdrip.online" },
    { label: "LAWCOLAB", url: "https://lawcolab.com" },
    { label: "YouTube", url: "https://youtube.com/@Taskdriper" },
  ],
  skills: [
    "JavaScript", "TypeScript", "React", "Next.js", "Node.js", "Express.js",
    "PostgreSQL", "MongoDB", "REST APIs", "AI integration", "Railway deployment",
    "WordPress", "SEO", "UI/UX", "Product strategy", "Digital marketing",
  ],
  services: [
    "SaaS product architecture",
    "AI-powered application development",
    "Business process automation",
    "Marketplace and LMS development",
    "Digital transformation consulting",
  ],
};

export const DEFAULT_PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    slug: "taskdrip",
    title: "Taskdrip",
    category: "Marketplace · Fintech · Learning",
    year: "2025–Present",
    summary: "A creator marketplace that connects brands and influencers through campaigns, escrow, direct hire, and education.",
    description: "Taskdrip brings creator discovery, campaign operations, crypto-enabled payments, digital products, community, and BreedSkool learning into one platform. The product is designed around trust: verified profiles, structured campaign submissions, admin-controlled payment flows, and clear progress visibility.",
    role: "Founder · Product architect · Lead engineer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Drizzle ORM", "WebSockets", "Railway"],
    outcomes: ["One workspace for creator campaigns, products, education, and direct hire", "Escrow and review flows designed around transparent delivery", "Admin tooling for content, payments, users, and operations"],
    imageUrl: projectImage("photo-1556761175-b413da4baf72"),
    liveUrl: "https://taskdrip.online",
    featured: true,
    visible: true,
    sortOrder: 1,
  },
  {
    slug: "beagvs-marine",
    title: "Beagvs Marine",
    category: "Corporate · Marine Services",
    year: "2024",
    summary: "A professional digital presence for a marine services business with a clear path from credibility to enquiry.",
    description: "Beagvs Marine presents a service-led brand with structured information architecture, responsive layouts, and conversion-focused contact journeys. The project translates a specialist business into a digital experience that is easier for prospective clients to understand and trust.",
    role: "Digital transformation consultant · Developer",
    technologies: ["React", "Responsive UI", "SEO", "Content architecture"],
    outcomes: ["Clear service communication for a specialist audience", "Mobile-first experience for enquiry-led browsing", "A reusable foundation for future service expansion"],
    imageUrl: projectImage("photo-1494412574643-ff11b0a5c1c3"),
    liveUrl: "",
    featured: true,
    visible: true,
    sortOrder: 2,
  },
  {
    slug: "lawcolab",
    title: "LAWCOLAB",
    category: "LegalTech · SaaS",
    year: "2024–Present",
    summary: "A legal practice operating system for matters, clients, documents, invoicing, and firm operations.",
    description: "LAWCOLAB turns everyday law-firm operations into a connected workspace. It supports client and matter management, document workflows, billing, team visibility, and a client portal — helping legal professionals spend less time stitching together disconnected tools.",
    role: "Founder · Product architect · Lead engineer",
    technologies: ["Python", "Flask", "PostgreSQL", "REST APIs", "Multi-tenant SaaS"],
    outcomes: ["Connected operational workflows for modern legal practices", "Multi-tenant foundation built for solo practitioners and growing firms", "A product shaped by legal practice knowledge and software discipline"],
    imageUrl: projectImage("photo-1450101499163-c8848c66ca85"),
    liveUrl: "https://lawcolab.com",
    featured: true,
    visible: true,
    sortOrder: 3,
  },
  {
    slug: "stageplug",
    title: "StagePlug",
    category: "Events · Marketplace",
    year: "2024",
    summary: "An event and entertainment platform concept connecting organizers, talent, and production needs.",
    description: "StagePlug is built around the practical coordination challenges behind events: finding the right people, presenting opportunities clearly, and turning discovery into action. The experience balances marketplace browsing with the detail needed for high-trust event work.",
    role: "Product architect · Full-stack developer",
    technologies: ["React", "Node.js", "PostgreSQL", "Marketplace UX"],
    outcomes: ["A focused discovery experience for event stakeholders", "Structured listings that make complex services easier to compare", "A foundation for bookings, profiles, and production workflows"],
    imageUrl: projectImage("photo-1501281668745-f7f57925c3b4"),
    liveUrl: "",
    featured: true,
    visible: true,
    sortOrder: 4,
  },
  {
    slug: "the-industry-miner",
    title: "The Industry Miner",
    category: "Media · Research",
    year: "2024",
    summary: "A research and media product focused on surfacing useful industry intelligence.",
    description: "The Industry Miner is a content-led digital product for organizing insights, stories, and opportunities into a more discoverable experience. Its visual system is designed to make dense subject matter feel approachable without losing editorial depth.",
    role: "Product designer · Developer",
    technologies: ["React", "Content systems", "SEO", "Editorial UX"],
    outcomes: ["Structured publishing experience for industry-focused content", "Better pathways from headline discovery to deeper reading", "A flexible base for research, reports, and sponsored content"],
    imageUrl: projectImage("photo-1454165804606-c3d57bc86b40"),
    liveUrl: "",
    featured: true,
    visible: true,
    sortOrder: 5,
  },
  {
    slug: "property-os",
    title: "Property OS",
    category: "PropTech · SaaS",
    year: "2023–Present",
    summary: "A property management SaaS concept for organizing properties, tenants, maintenance, and business operations.",
    description: "Property OS brings the operational side of property management into one place. The product direction focuses on replacing fragmented spreadsheets and chat threads with structured records, task visibility, and actionable dashboards.",
    role: "Product architect · Full-stack developer",
    technologies: ["React", "Node.js", "PostgreSQL", "Dashboards", "Workflow automation"],
    outcomes: ["Centralized view of property operations", "Clearer workflows for recurring management tasks", "An extensible platform direction for landlords and property teams"],
    imageUrl: projectImage("photo-1560518883-ce09059eeffa"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 6,
  },
  {
    slug: "ai-ebook-generator",
    title: "AI Ebook Generator",
    category: "AI · Content Tools",
    year: "2023",
    summary: "An AI-assisted workflow for turning ideas into structured ebook drafts and publishable content.",
    description: "The AI Ebook Generator explores how generative AI can support authors and businesses without hiding the human in the process. The workflow emphasizes guided inputs, useful structure, editing, and export rather than one-click noise.",
    role: "AI product architect · Developer",
    technologies: ["AI APIs", "React", "Node.js", "Prompt design", "Document workflows"],
    outcomes: ["Guided creation flow from concept to structured draft", "Human-in-the-loop editing as a first-class step", "A reusable pattern for AI-assisted business content"],
    imageUrl: projectImage("photo-1456324504439-367cee3b3c32"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 7,
  },
  {
    slug: "breedskool-lms",
    title: "BreedSkool LMS",
    category: "EdTech · Learning",
    year: "2023–Present",
    summary: "A learning platform for practical technology training, courses, lessons, certificates, and community.",
    description: "BreedSkool extends the mission of Breedskool Galaxy Ltd into a modern learning experience. It supports course discovery, structured lessons, enrollment, progress, certificates, and training operations designed for aspiring creators and digital professionals.",
    role: "Founder · Learning product architect · Developer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Course workflows"],
    outcomes: ["Learning journeys that connect lessons to visible progress", "Admin controls for courses, pricing, enrollments, and certificates", "A scalable home for practical digital skills training"],
    imageUrl: projectImage("photo-1522202176988-66273c2fd55f"),
    liveUrl: "/breedskool",
    featured: false,
    visible: true,
    sortOrder: 8,
  },
  {
    slug: "full-stack-saas-starter",
    title: "Full-Stack SaaS Starter",
    category: "Developer Tools · SaaS",
    year: "2023",
    summary: "A production-minded starter system for building authenticated, data-driven SaaS products faster.",
    description: "This starter product packages the recurring foundations of a modern SaaS application: authentication, dashboards, payments, content, database-backed workflows, and deployment practices. It is designed to help founders move from idea to a credible first release with less reinvention.",
    role: "Software architect · Developer",
    technologies: ["React", "TypeScript", "Express", "PostgreSQL", "Drizzle ORM", "Vite"],
    outcomes: ["Reusable patterns for product teams starting a new SaaS", "Clear separation between platform foundations and feature work", "A practical bridge from prototype to production"],
    imageUrl: projectImage("photo-1518770660439-4636190af475"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 9,
  },
  {
    slug: "influencer-media-kit",
    title: "Influencer Media Kit",
    category: "Creator Tools · Template",
    year: "2023",
    summary: "A polished media kit system that helps creators present their audience, services, and partnership value.",
    description: "The Influencer Media Kit gives creators a stronger way to communicate who they are and how brands can work with them. The design focuses on scannable proof, clear offers, and a personal brand presentation that feels more considered than a collection of social links.",
    role: "Product designer · Developer",
    technologies: ["React", "Responsive UI", "Brand systems", "Creator UX"],
    outcomes: ["A clear narrative for creator-brand conversations", "Reusable content blocks for different creator niches", "A stronger bridge between audience data and commercial opportunity"],
    imageUrl: projectImage("photo-1521737711867-e3b97375f902"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 10,
  },
  {
    slug: "viral-content-templates",
    title: "Viral Content Templates",
    category: "Creator Tools · Template",
    year: "2023",
    summary: "A practical content template library for creators who need repeatable ideas and faster production.",
    description: "Viral Content Templates organizes content prompts and formats into a usable system rather than a static list of inspiration. It is designed to help creators move from an idea to a publishable brief with less friction.",
    role: "Content product designer · Developer",
    technologies: ["Content systems", "React", "UX writing", "Information architecture"],
    outcomes: ["Faster discovery of relevant content formats", "A repeatable workflow for planning creator output", "A foundation for personalization by niche and platform"],
    imageUrl: projectImage("photo-1516321318423-f06f85e504b3"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 11,
  },
  {
    slug: "hashtag-research-tool-pro",
    title: "Hashtag Research Tool Pro",
    category: "Creator Tools · Analytics",
    year: "2023",
    summary: "A focused research tool for helping creators make more informed content distribution choices.",
    description: "Hashtag Research Tool Pro turns a noisy discovery problem into a more focused research workflow. The product direction is centered on useful filtering, understandable signals, and decisions creators can act on immediately.",
    role: "Product architect · Developer",
    technologies: ["React", "Data visualization", "Search UX", "API integration"],
    outcomes: ["More deliberate discovery and content planning", "Signals presented in a way non-technical users can understand", "A modular base for broader creator analytics"],
    imageUrl: projectImage("photo-1551288049-bebda4e38f71"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 12,
  },
  {
    slug: "content-influencer-toolkit",
    title: "Content Influencer Toolkit",
    category: "Creator Tools · Productivity",
    year: "2023",
    summary: "A collection of practical workflows and tools for creators building a consistent publishing business.",
    description: "The Content Influencer Toolkit brings planning, content operations, and creator resources into a single product direction. It is intentionally practical: reduce the blank-page problem, make repeatable work easier, and keep the creator focused on their audience.",
    role: "Product strategist · Developer",
    technologies: ["React", "Content workflows", "UI systems", "Digital products"],
    outcomes: ["A cohesive home for everyday creator workflows", "Reusable patterns for tool and resource libraries", "A product foundation that supports both free and premium content"],
    imageUrl: projectImage("photo-1499750310107-5fef28a66643"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 13,
  },
  {
    slug: "personal-brand-strategy-guide",
    title: "Personal Brand Strategy Guide",
    category: "Strategy · Digital Product",
    year: "2023",
    summary: "A guided digital product for creators and professionals shaping a clearer personal brand.",
    description: "The Personal Brand Strategy Guide helps users move from a vague sense of what they do to a clearer positioning story. It combines prompts, frameworks, and practical next steps so the result can live across a profile, portfolio, and content plan.",
    role: "Brand strategist · Product designer",
    technologies: ["Brand strategy", "UX writing", "Digital publishing", "Content design"],
    outcomes: ["A clearer process for defining a differentiated point of view", "Frameworks that translate into content and profile decisions", "A reusable digital product for personal brand workshops"],
    imageUrl: projectImage("photo-1497215728101-856f4ea42174"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 14,
  },
  {
    slug: "github-repo-growth-kit",
    title: "GitHub Repo Growth Kit",
    category: "Developer Tools · Documentation",
    year: "2023",
    summary: "A documentation and repository presentation system that helps open-source projects earn trust.",
    description: "The GitHub Repo Growth Kit treats documentation as part of the product experience. It gives maintainers a clearer structure for README content, contribution guidance, issue templates, releases, and the first impression that turns a visitor into a user or contributor.",
    role: "Developer experience designer · Developer",
    technologies: ["GitHub", "Documentation systems", "Markdown", "Open-source workflows"],
    outcomes: ["More navigable repositories for users and contributors", "Repeatable documentation patterns for new projects", "A stronger connection between code quality and product communication"],
    imageUrl: projectImage("photo-1555066931-4365d14bab8c"),
    liveUrl: "",
    featured: false,
    visible: true,
    sortOrder: 15,
  },
];

export const PORTFOLIO_CONTENT_KEYS = {
  profile: "portfolio_abraham_profile",
  projects: "portfolio_abraham_projects",
} as const;